# Generated by Django 6.0.6 on 2026-07-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('I', 'I Lapso'), ('II', 'II Lapso'), ('III', 'III Lapso')], max_length=10)),
                ('objetivo', models.TextField()),
                ('metodo', models.CharField(max_length=100)),
                ('puntuacion_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='app_academico.aulavirtual')),
            ],
            options={
                'db_table': 'planes_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_evaluaciones.planevaluacion')),
            ],
            options={
                'db_table': 'actividades',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_evaluaciones.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_academico.estudiante')),
            ],
            options={
                'db_table': 'calificaciones',
                'ordering': ['-fecha_registro'],
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
        migrations.AddConstraint(
            model_name='planevaluacion',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion_max__lte', 20)), name='puntuacion_max_menor_igual_20'),
        ),
    ]
