# Generated by Django 6.0.6 on 2026-07-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academico', '0002_initial'),
        ('app_evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_academico.estudiante'),
        ),
        migrations.AddField(
            model_name='planevaluacion',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='app_academico.aulavirtual'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_evaluaciones.planevaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('actividad', 'estudiante')},
        ),
        migrations.AddConstraint(
            model_name='planevaluacion',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion_max__lte', 20)), name='puntuacion_max_menor_igual_20'),
        ),
    ]
