# Generated by Django 6.0.6 on 2026-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluacion',
            name='objetivos_detallados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
