# Generated by Django 6.0.6 on 2026-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluaciones', '0003_planevaluacion_objetivos_detallados'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluacion',
            name='aprobado_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
