# Generated by Django 6.0.6 on 2026-07-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0002_initial'),
        ('app_evaluaciones', '0004_planevaluacion_aprobado_por_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluacion',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EvaluacionObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=500)),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_objetivo', to='app_academico.estudiante')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_objetivo', to='app_evaluaciones.planevaluacion')),
            ],
            options={
                'db_table': 'evaluaciones_objetivo',
                'ordering': ['-fecha_registro'],
                'unique_together': {('plan', 'estudiante', 'objetivo')},
            },
        ),
    ]
