# Generated by Django 6.0.6 on 2026-07-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0003_aulavirtual_catedra'),
        ('app_evaluaciones', '0005_planevaluacion_finalizado_evaluacionobjetivo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionobjetivo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evaluacionobjetivo',
            name='objetivo_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionobjetivo',
            unique_together={('plan', 'estudiante', 'objetivo_index')},
        ),
    ]
