# Generated by Django 6.0.6 on 2026-07-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluaciones', '0006_alter_evaluacionobjetivo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluacion',
            name='notas_enviadas_al_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planevaluacion',
            name='publicado_para_estudiantes',
            field=models.BooleanField(default=False),
        ),
    ]
