# Generated by Django 6.0.6 on 2026-07-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0003_aulavirtual_catedra'),
        ('app_evaluaciones', '0007_planevaluacion_notas_enviadas_al_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPublicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_publicadas', to='app_academico.estudiante')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_publicadas', to='app_evaluaciones.planevaluacion')),
            ],
            options={
                'db_table': 'notas_publicadas',
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('plan', 'estudiante')},
            },
        ),
    ]
