# Generated by Django 6.0.6 on 2026-07-09 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('representante', models.CharField(max_length=200)),
                ('telefono_representante', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesor', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='AulaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_curso', models.IntegerField(choices=[(1, '1° Año'), (2, '2° Año'), (3, '3° Año'), (4, '4° Año'), (5, '5° Año')])),
                ('lapsos', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='app_academico.profesor')),
            ],
            options={
                'db_table': 'aulas_virtuales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_academico.aulavirtual')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_academico.estudiante')),
            ],
            options={
                'db_table': 'matriculas',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'aula')},
            },
        ),
    ]
