# Generated by Django 6.0.6 on 2026-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulavirtual',
            name='catedra',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
