from django.urls import path

from .views import (
    ActividadCreateView,
    ActividadDeleteView,
    ActividadUpdateView,
    AsignarEstudianteView,
    EstudianteAulasListView,
    EstudianteDashboardView,
    EstudianteDetalleAulaView,
    EstudiantePlanDetailView,
    EstudiantePlanesView,
    EstudiantePreviewCalificacionesView,
    EvaluarObjetivoView,
    EvaluarPlanView,
    GuardarNotasView,
    EnviarNotasAdminView,
    MatrizNotasView,
    ReporteNotasView,
    PlanEvaluacionCreateView,
    PlanEvaluacionDeleteView,
    PlanEvaluacionDetailView,
    PlanEvaluacionListView,
    PlanEvaluacionUpdateView,
    ProfesorAulaDetailView,
    ProfesorAulaListView,
    ProfesorDashboardView,
    ProfesorEstudianteDetailView,
    ProfesorEstudianteListView,
)

app_name = 'evaluaciones'

urlpatterns = [
    path('profesor/dashboard/', ProfesorDashboardView.as_view(), name='profesor_dashboard'),
    path('profesor/aulas/', ProfesorAulaListView.as_view(), name='profesor_aulas'),
    path('profesor/aulas/<int:pk>/', ProfesorAulaDetailView.as_view(), name='profesor_aula_detalle'),
    path('profesor/estudiantes/', ProfesorEstudianteListView.as_view(), name='profesor_estudiantes'),
    path('profesor/estudiantes/<int:pk>/', ProfesorEstudianteDetailView.as_view(), name='profesor_estudiante_detalle'),
    path('profesor/planes/', PlanEvaluacionListView.as_view(), name='profesor_planes'),
    path('profesor/planes/<int:pk>/', PlanEvaluacionDetailView.as_view(), name='profesor_plan_detalle'),
    path('profesor/planes/<int:pk>/evaluar/', EvaluarPlanView.as_view(), name='profesor_plan_evaluar'),
    path('profesor/planes/<int:pk>/objetivos/<int:objetivo_index>/evaluar/', EvaluarObjetivoView.as_view(), name='profesor_objetivo_evaluar'),
    path('profesor/planes/nuevo/', PlanEvaluacionCreateView.as_view(), name='profesor_plan_nuevo'),
    path('profesor/planes/<int:pk>/editar/', PlanEvaluacionUpdateView.as_view(), name='profesor_plan_editar'),
    path('profesor/planes/<int:pk>/eliminar/', PlanEvaluacionDeleteView.as_view(), name='profesor_plan_eliminar'),
    path('profesor/planes/<int:plan_pk>/actividades/nuevo/', ActividadCreateView.as_view(), name='profesor_actividad_nuevo'),
    path('profesor/actividades/<int:pk>/editar/', ActividadUpdateView.as_view(), name='profesor_actividad_editar'),
    path('profesor/actividades/<int:pk>/eliminar/', ActividadDeleteView.as_view(), name='profesor_actividad_eliminar'),
    path('profesor/asignar-estudiante/', AsignarEstudianteView.as_view(), name='profesor_asignar_estudiante'),
    path('profesor/matriz-notas/<int:pk_aula>/', MatrizNotasView.as_view(), name='profesor_matriz_notas'),
    path('profesor/guardar-notas/', GuardarNotasView.as_view(), name='profesor_guardar_notas'),
    path('profesor/aulas/<int:pk_aula>/enviar-notas-admin/', EnviarNotasAdminView.as_view(), name='profesor_enviar_notas_admin'),
    path('profesor/planes/<int:pk>/reporte-notas/', ReporteNotasView.as_view(), name='profesor_reporte_notas'),
    path('estudiante/dashboard/', EstudianteDashboardView.as_view(), name='estudiante_dashboard'),
    path('estudiante/aulas/', EstudianteAulasListView.as_view(), name='estudiante_aulas'),
    path('estudiante/aula/<int:pk>/', EstudianteDetalleAulaView.as_view(), name='estudiante_aula_detalle'),
    path('estudiante/planes/', EstudiantePlanesView.as_view(), name='estudiante_planes'),
    path('estudiante/planes/<int:pk>/', EstudiantePlanDetailView.as_view(), name='estudiante_plan_detalle'),
    path('estudiante/calificaciones/', EstudiantePreviewCalificacionesView.as_view(), name='estudiante_calificaciones'),
]